/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WatchLiveRouteImport } from './routes/watch-live'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SubmitNewsTipRouteImport } from './routes/submit-news-tip'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PublicFileRouteImport } from './routes/public-file'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as CorrectionsPolicyRouteImport } from './routes/corrections-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as MerchIndexRouteImport } from './routes/merch.index'
import { Route as WeatherClosingsRouteImport } from './routes/weather.closings'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as StationVerifyRouteImport } from './routes/station.verify'
import { Route as StationAdminRouteImport } from './routes/station.admin'
import { Route as NewsLocalRouteImport } from './routes/news.local'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as NetworkSiteSlugRouteImport } from './routes/network_.$siteSlug'
import { Route as NetworkStationsRouteImport } from './routes/network.stations'
import { Route as NetworkDocsRouteImport } from './routes/network.docs'
import { Route as NetworkChangelogRouteImport } from './routes/network.changelog'
import { Route as MerchIdRouteImport } from './routes/merch.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutMerchReturnRouteImport } from './routes/checkout.merch-return'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as NetworkSiteSlugIndexRouteImport } from './routes/network_.$siteSlug.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as NetworkSiteSlugWeatherRouteImport } from './routes/network_.$siteSlug.weather'
import { Route as NetworkSiteSlugWatchLiveRouteImport } from './routes/network_.$siteSlug.watch-live'
import { Route as NetworkSiteSlugTermsRouteImport } from './routes/network_.$siteSlug.terms'
import { Route as NetworkSiteSlugSportsRouteImport } from './routes/network_.$siteSlug.sports'
import { Route as NetworkSiteSlugShowsRouteImport } from './routes/network_.$siteSlug.shows'
import { Route as NetworkSiteSlugPrivacyRouteImport } from './routes/network_.$siteSlug.privacy'
import { Route as NetworkSiteSlugDmcaRouteImport } from './routes/network_.$siteSlug.dmca'
import { Route as NetworkSiteSlugContactRouteImport } from './routes/network_.$siteSlug.contact'
import { Route as NetworkSiteSlugAdminRouteImport } from './routes/network_.$siteSlug.admin'
import { Route as NetworkSiteSlugAboutRouteImport } from './routes/network_.$siteSlug.about'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAdminVerdictRouteImport } from './routes/_authenticated/admin.verdict'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminSiteContentRouteImport } from './routes/_authenticated/admin.site-content'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReleasesRouteImport } from './routes/_authenticated/admin.releases'
import { Route as AuthenticatedAdminRedditAutomationRouteImport } from './routes/_authenticated/admin.reddit-automation'
import { Route as AuthenticatedAdminRedditRouteImport } from './routes/_authenticated/admin.reddit'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminMerchSettingsRouteImport } from './routes/_authenticated/admin.merch-settings'
import { Route as AuthenticatedAdminMerchRouteImport } from './routes/_authenticated/admin.merch'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminManagedSitesRouteImport } from './routes/_authenticated/admin.managed-sites'
import { Route as AuthenticatedAdminLicensesRouteImport } from './routes/_authenticated/admin.licenses'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminCommentsRouteImport } from './routes/_authenticated/admin.comments'
import { Route as AuthenticatedAdminClosingsRouteImport } from './routes/_authenticated/admin.closings'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminAuthorsRouteImport } from './routes/_authenticated/admin.authors'
import { Route as AuthenticatedAdminAiLogRouteImport } from './routes/_authenticated/admin.ai-log'
import { Route as AuthenticatedAdminAbuseRouteImport } from './routes/_authenticated/admin.abuse'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAccountLicensesRouteImport } from './routes/_authenticated/account.licenses'
import { Route as NetworkSiteSlugNewsIndexRouteImport } from './routes/network_.$siteSlug.news.index'
import { Route as AuthenticatedAccountManagedSitesIndexRouteImport } from './routes/_authenticated/account.managed-sites.index'
import { Route as NetworkSiteSlugNewsSlugRouteImport } from './routes/network_.$siteSlug.news.$slug'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebStoriesSlugRouteImport } from './routes/api/public/web-stories.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicNetworkIngestReleaseRouteImport } from './routes/api/public/network/ingest-release'
import { Route as ApiPublicNetworkCheckUpdateRouteImport } from './routes/api/public/network/check-update'
import { Route as ApiPublicHooksVerdictGhostTickRouteImport } from './routes/api/public/hooks/verdict-ghost-tick'
import { Route as ApiPublicHooksRetryMerchRouteImport } from './routes/api/public/hooks/retry-merch'
import { Route as ApiPublicHooksRedditListingJobRouteImport } from './routes/api/public/hooks/reddit-listing-job'
import { Route as ApiPublicHooksRedditListingCallbackRouteImport } from './routes/api/public/hooks/reddit-listing-callback'
import { Route as ApiPublicHooksRedditCommentJobRouteImport } from './routes/api/public/hooks/reddit-comment-job'
import { Route as ApiPublicHooksRedditCommentCallbackRouteImport } from './routes/api/public/hooks/reddit-comment-callback'
import { Route as ApiPublicHooksProcessPendingRouteImport } from './routes/api/public/hooks/process-pending'
import { Route as ApiPublicHooksManualJsonlImportRouteImport } from './routes/api/public/hooks/manual-jsonl-import'
import { Route as ApiPublicHooksBackfillCommentsRouteImport } from './routes/api/public/hooks/backfill-comments'
import { Route as AuthenticatedAdminRedditIdRouteImport } from './routes/_authenticated/admin.reddit.$id'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin.posts.$id'
import { Route as AuthenticatedAdminNetworkHealthRouteImport } from './routes/_authenticated/admin.network.health'
import { Route as AuthenticatedAdminImportBatchIdRouteImport } from './routes/_authenticated/admin.import.$batchId'
import { Route as ApiPublicIntegrationsSupabaseCallbackRouteImport } from './routes/api/public/integrations/supabase/callback'
import { Route as AuthenticatedAccountManagedSitesSiteIdOnboardingRouteImport } from './routes/_authenticated/account.managed-sites.$siteId.onboarding'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLiveRoute = WatchLiveRouteImport.update({
  id: '/watch-live',
  path: '/watch-live',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitNewsTipRoute = SubmitNewsTipRouteImport.update({
  id: '/submit-news-tip',
  path: '/submit-news-tip',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicFileRoute = PublicFileRouteImport.update({
  id: '/public-file',
  path: '/public-file',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsPolicyRoute = CorrectionsPolicyRouteImport.update({
  id: '/corrections-policy',
  path: '/corrections-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchIndexRoute = MerchIndexRouteImport.update({
  id: '/merch/',
  path: '/merch/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherClosingsRoute = WeatherClosingsRouteImport.update({
  id: '/closings',
  path: '/closings',
  getParentRoute: () => WeatherRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StationVerifyRoute = StationVerifyRouteImport.update({
  id: '/station/verify',
  path: '/station/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StationAdminRoute = StationAdminRouteImport.update({
  id: '/station/admin',
  path: '/station/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsLocalRoute = NewsLocalRouteImport.update({
  id: '/news/local',
  path: '/news/local',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkSiteSlugRoute = NetworkSiteSlugRouteImport.update({
  id: '/network_/$siteSlug',
  path: '/network/$siteSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkStationsRoute = NetworkStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => NetworkRoute,
} as any)
const NetworkDocsRoute = NetworkDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => NetworkRoute,
} as any)
const NetworkChangelogRoute = NetworkChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => NetworkRoute,
} as any)
const MerchIdRoute = MerchIdRouteImport.update({
  id: '/merch/$id',
  path: '/merch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutMerchReturnRoute = CheckoutMerchReturnRouteImport.update({
  id: '/checkout/merch-return',
  path: '/checkout/merch-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NetworkSiteSlugIndexRoute = NetworkSiteSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const NetworkSiteSlugWeatherRoute = NetworkSiteSlugWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugWatchLiveRoute =
  NetworkSiteSlugWatchLiveRouteImport.update({
    id: '/watch-live',
    path: '/watch-live',
    getParentRoute: () => NetworkSiteSlugRoute,
  } as any)
const NetworkSiteSlugTermsRoute = NetworkSiteSlugTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugSportsRoute = NetworkSiteSlugSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugShowsRoute = NetworkSiteSlugShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugPrivacyRoute = NetworkSiteSlugPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugDmcaRoute = NetworkSiteSlugDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugContactRoute = NetworkSiteSlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugAdminRoute = NetworkSiteSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const NetworkSiteSlugAboutRoute = NetworkSiteSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVerdictRoute =
  AuthenticatedAdminVerdictRouteImport.update({
    id: '/verdict',
    path: '/verdict',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSiteContentRoute =
  AuthenticatedAdminSiteContentRouteImport.update({
    id: '/site-content',
    path: '/site-content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReleasesRoute =
  AuthenticatedAdminReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRedditAutomationRoute =
  AuthenticatedAdminRedditAutomationRouteImport.update({
    id: '/reddit-automation',
    path: '/reddit-automation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRedditRoute =
  AuthenticatedAdminRedditRouteImport.update({
    id: '/reddit',
    path: '/reddit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMerchSettingsRoute =
  AuthenticatedAdminMerchSettingsRouteImport.update({
    id: '/merch-settings',
    path: '/merch-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMerchRoute = AuthenticatedAdminMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminManagedSitesRoute =
  AuthenticatedAdminManagedSitesRouteImport.update({
    id: '/managed-sites',
    path: '/managed-sites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLicensesRoute =
  AuthenticatedAdminLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClosingsRoute =
  AuthenticatedAdminClosingsRouteImport.update({
    id: '/closings',
    path: '/closings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuthorsRoute =
  AuthenticatedAdminAuthorsRouteImport.update({
    id: '/authors',
    path: '/authors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiLogRoute = AuthenticatedAdminAiLogRouteImport.update({
  id: '/ai-log',
  path: '/ai-log',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAbuseRoute = AuthenticatedAdminAbuseRouteImport.update({
  id: '/abuse',
  path: '/abuse',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountLicensesRoute =
  AuthenticatedAccountLicensesRouteImport.update({
    id: '/account/licenses',
    path: '/account/licenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const NetworkSiteSlugNewsIndexRoute =
  NetworkSiteSlugNewsIndexRouteImport.update({
    id: '/news/',
    path: '/news/',
    getParentRoute: () => NetworkSiteSlugRoute,
  } as any)
const AuthenticatedAccountManagedSitesIndexRoute =
  AuthenticatedAccountManagedSitesIndexRouteImport.update({
    id: '/account/managed-sites/',
    path: '/account/managed-sites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const NetworkSiteSlugNewsSlugRoute = NetworkSiteSlugNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => NetworkSiteSlugRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebStoriesSlugRoute = ApiPublicWebStoriesSlugRouteImport.update({
  id: '/api/public/web-stories/$slug',
  path: '/api/public/web-stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNetworkIngestReleaseRoute =
  ApiPublicNetworkIngestReleaseRouteImport.update({
    id: '/api/public/network/ingest-release',
    path: '/api/public/network/ingest-release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNetworkCheckUpdateRoute =
  ApiPublicNetworkCheckUpdateRouteImport.update({
    id: '/api/public/network/check-update',
    path: '/api/public/network/check-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerdictGhostTickRoute =
  ApiPublicHooksVerdictGhostTickRouteImport.update({
    id: '/api/public/hooks/verdict-ghost-tick',
    path: '/api/public/hooks/verdict-ghost-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRetryMerchRoute =
  ApiPublicHooksRetryMerchRouteImport.update({
    id: '/api/public/hooks/retry-merch',
    path: '/api/public/hooks/retry-merch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRedditListingJobRoute =
  ApiPublicHooksRedditListingJobRouteImport.update({
    id: '/api/public/hooks/reddit-listing-job',
    path: '/api/public/hooks/reddit-listing-job',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRedditListingCallbackRoute =
  ApiPublicHooksRedditListingCallbackRouteImport.update({
    id: '/api/public/hooks/reddit-listing-callback',
    path: '/api/public/hooks/reddit-listing-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRedditCommentJobRoute =
  ApiPublicHooksRedditCommentJobRouteImport.update({
    id: '/api/public/hooks/reddit-comment-job',
    path: '/api/public/hooks/reddit-comment-job',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRedditCommentCallbackRoute =
  ApiPublicHooksRedditCommentCallbackRouteImport.update({
    id: '/api/public/hooks/reddit-comment-callback',
    path: '/api/public/hooks/reddit-comment-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessPendingRoute =
  ApiPublicHooksProcessPendingRouteImport.update({
    id: '/api/public/hooks/process-pending',
    path: '/api/public/hooks/process-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksManualJsonlImportRoute =
  ApiPublicHooksManualJsonlImportRouteImport.update({
    id: '/api/public/hooks/manual-jsonl-import',
    path: '/api/public/hooks/manual-jsonl-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillCommentsRoute =
  ApiPublicHooksBackfillCommentsRouteImport.update({
    id: '/api/public/hooks/backfill-comments',
    path: '/api/public/hooks/backfill-comments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRedditIdRoute =
  AuthenticatedAdminRedditIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRedditRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPostsRoute,
  } as any)
const AuthenticatedAdminNetworkHealthRoute =
  AuthenticatedAdminNetworkHealthRouteImport.update({
    id: '/network/health',
    path: '/network/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportBatchIdRoute =
  AuthenticatedAdminImportBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedAdminImportRoute,
  } as any)
const ApiPublicIntegrationsSupabaseCallbackRoute =
  ApiPublicIntegrationsSupabaseCallbackRouteImport.update({
    id: '/api/public/integrations/supabase/callback',
    path: '/api/public/integrations/supabase/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountManagedSitesSiteIdOnboardingRoute =
  AuthenticatedAccountManagedSitesSiteIdOnboardingRouteImport.update({
    id: '/account/managed-sites/$siteId/onboarding',
    path: '/account/managed-sites/$siteId/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/network': typeof NetworkRouteWithChildren
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-file': typeof PublicFileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/submit-news-tip': typeof SubmitNewsTipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/checkout/merch-return': typeof CheckoutMerchReturnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/merch/$id': typeof MerchIdRoute
  '/network/changelog': typeof NetworkChangelogRoute
  '/network/docs': typeof NetworkDocsRoute
  '/network/stations': typeof NetworkStationsRoute
  '/network/$siteSlug': typeof NetworkSiteSlugRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/news/local': typeof NewsLocalRoute
  '/station/admin': typeof StationAdminRoute
  '/station/verify': typeof StationVerifyRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/weather/closings': typeof WeatherClosingsRoute
  '/merch/': typeof MerchIndexRoute
  '/news/': typeof NewsIndexRoute
  '/account/licenses': typeof AuthenticatedAccountLicensesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/admin/ai-log': typeof AuthenticatedAdminAiLogRoute
  '/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/closings': typeof AuthenticatedAdminClosingsRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/import': typeof AuthenticatedAdminImportRouteWithChildren
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/managed-sites': typeof AuthenticatedAdminManagedSitesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/merch': typeof AuthenticatedAdminMerchRoute
  '/admin/merch-settings': typeof AuthenticatedAdminMerchSettingsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/admin/reddit': typeof AuthenticatedAdminRedditRouteWithChildren
  '/admin/reddit-automation': typeof AuthenticatedAdminRedditAutomationRoute
  '/admin/releases': typeof AuthenticatedAdminReleasesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/verdict': typeof AuthenticatedAdminVerdictRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/network/$siteSlug/about': typeof NetworkSiteSlugAboutRoute
  '/network/$siteSlug/admin': typeof NetworkSiteSlugAdminRoute
  '/network/$siteSlug/contact': typeof NetworkSiteSlugContactRoute
  '/network/$siteSlug/dmca': typeof NetworkSiteSlugDmcaRoute
  '/network/$siteSlug/privacy': typeof NetworkSiteSlugPrivacyRoute
  '/network/$siteSlug/shows': typeof NetworkSiteSlugShowsRoute
  '/network/$siteSlug/sports': typeof NetworkSiteSlugSportsRoute
  '/network/$siteSlug/terms': typeof NetworkSiteSlugTermsRoute
  '/network/$siteSlug/watch-live': typeof NetworkSiteSlugWatchLiveRoute
  '/network/$siteSlug/weather': typeof NetworkSiteSlugWeatherRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/network/$siteSlug/': typeof NetworkSiteSlugIndexRoute
  '/admin/import/$batchId': typeof AuthenticatedAdminImportBatchIdRoute
  '/admin/network/health': typeof AuthenticatedAdminNetworkHealthRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/reddit/$id': typeof AuthenticatedAdminRedditIdRoute
  '/api/public/hooks/backfill-comments': typeof ApiPublicHooksBackfillCommentsRoute
  '/api/public/hooks/manual-jsonl-import': typeof ApiPublicHooksManualJsonlImportRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/hooks/reddit-comment-callback': typeof ApiPublicHooksRedditCommentCallbackRoute
  '/api/public/hooks/reddit-comment-job': typeof ApiPublicHooksRedditCommentJobRoute
  '/api/public/hooks/reddit-listing-callback': typeof ApiPublicHooksRedditListingCallbackRoute
  '/api/public/hooks/reddit-listing-job': typeof ApiPublicHooksRedditListingJobRoute
  '/api/public/hooks/retry-merch': typeof ApiPublicHooksRetryMerchRoute
  '/api/public/hooks/verdict-ghost-tick': typeof ApiPublicHooksVerdictGhostTickRoute
  '/api/public/network/check-update': typeof ApiPublicNetworkCheckUpdateRoute
  '/api/public/network/ingest-release': typeof ApiPublicNetworkIngestReleaseRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/web-stories/$slug': typeof ApiPublicWebStoriesSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/network/$siteSlug/news/$slug': typeof NetworkSiteSlugNewsSlugRoute
  '/account/managed-sites/': typeof AuthenticatedAccountManagedSitesIndexRoute
  '/network/$siteSlug/news/': typeof NetworkSiteSlugNewsIndexRoute
  '/account/managed-sites/$siteId/onboarding': typeof AuthenticatedAccountManagedSitesSiteIdOnboardingRoute
  '/api/public/integrations/supabase/callback': typeof ApiPublicIntegrationsSupabaseCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/network': typeof NetworkRouteWithChildren
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-file': typeof PublicFileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/submit-news-tip': typeof SubmitNewsTipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/checkout/merch-return': typeof CheckoutMerchReturnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/merch/$id': typeof MerchIdRoute
  '/network/changelog': typeof NetworkChangelogRoute
  '/network/docs': typeof NetworkDocsRoute
  '/network/stations': typeof NetworkStationsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/local': typeof NewsLocalRoute
  '/station/admin': typeof StationAdminRoute
  '/station/verify': typeof StationVerifyRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/weather/closings': typeof WeatherClosingsRoute
  '/merch': typeof MerchIndexRoute
  '/news': typeof NewsIndexRoute
  '/account/licenses': typeof AuthenticatedAccountLicensesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/admin/ai-log': typeof AuthenticatedAdminAiLogRoute
  '/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/closings': typeof AuthenticatedAdminClosingsRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/import': typeof AuthenticatedAdminImportRouteWithChildren
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/managed-sites': typeof AuthenticatedAdminManagedSitesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/merch': typeof AuthenticatedAdminMerchRoute
  '/admin/merch-settings': typeof AuthenticatedAdminMerchSettingsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/admin/reddit': typeof AuthenticatedAdminRedditRouteWithChildren
  '/admin/reddit-automation': typeof AuthenticatedAdminRedditAutomationRoute
  '/admin/releases': typeof AuthenticatedAdminReleasesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/verdict': typeof AuthenticatedAdminVerdictRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/network/$siteSlug/about': typeof NetworkSiteSlugAboutRoute
  '/network/$siteSlug/admin': typeof NetworkSiteSlugAdminRoute
  '/network/$siteSlug/contact': typeof NetworkSiteSlugContactRoute
  '/network/$siteSlug/dmca': typeof NetworkSiteSlugDmcaRoute
  '/network/$siteSlug/privacy': typeof NetworkSiteSlugPrivacyRoute
  '/network/$siteSlug/shows': typeof NetworkSiteSlugShowsRoute
  '/network/$siteSlug/sports': typeof NetworkSiteSlugSportsRoute
  '/network/$siteSlug/terms': typeof NetworkSiteSlugTermsRoute
  '/network/$siteSlug/watch-live': typeof NetworkSiteSlugWatchLiveRoute
  '/network/$siteSlug/weather': typeof NetworkSiteSlugWeatherRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/network/$siteSlug': typeof NetworkSiteSlugIndexRoute
  '/admin/import/$batchId': typeof AuthenticatedAdminImportBatchIdRoute
  '/admin/network/health': typeof AuthenticatedAdminNetworkHealthRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/reddit/$id': typeof AuthenticatedAdminRedditIdRoute
  '/api/public/hooks/backfill-comments': typeof ApiPublicHooksBackfillCommentsRoute
  '/api/public/hooks/manual-jsonl-import': typeof ApiPublicHooksManualJsonlImportRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/hooks/reddit-comment-callback': typeof ApiPublicHooksRedditCommentCallbackRoute
  '/api/public/hooks/reddit-comment-job': typeof ApiPublicHooksRedditCommentJobRoute
  '/api/public/hooks/reddit-listing-callback': typeof ApiPublicHooksRedditListingCallbackRoute
  '/api/public/hooks/reddit-listing-job': typeof ApiPublicHooksRedditListingJobRoute
  '/api/public/hooks/retry-merch': typeof ApiPublicHooksRetryMerchRoute
  '/api/public/hooks/verdict-ghost-tick': typeof ApiPublicHooksVerdictGhostTickRoute
  '/api/public/network/check-update': typeof ApiPublicNetworkCheckUpdateRoute
  '/api/public/network/ingest-release': typeof ApiPublicNetworkIngestReleaseRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/web-stories/$slug': typeof ApiPublicWebStoriesSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/network/$siteSlug/news/$slug': typeof NetworkSiteSlugNewsSlugRoute
  '/account/managed-sites': typeof AuthenticatedAccountManagedSitesIndexRoute
  '/network/$siteSlug/news': typeof NetworkSiteSlugNewsIndexRoute
  '/account/managed-sites/$siteId/onboarding': typeof AuthenticatedAccountManagedSitesSiteIdOnboardingRoute
  '/api/public/integrations/supabase/callback': typeof ApiPublicIntegrationsSupabaseCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/network': typeof NetworkRouteWithChildren
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-file': typeof PublicFileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/submit-news-tip': typeof SubmitNewsTipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/checkout/merch-return': typeof CheckoutMerchReturnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/merch/$id': typeof MerchIdRoute
  '/network/changelog': typeof NetworkChangelogRoute
  '/network/docs': typeof NetworkDocsRoute
  '/network/stations': typeof NetworkStationsRoute
  '/network_/$siteSlug': typeof NetworkSiteSlugRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/news/local': typeof NewsLocalRoute
  '/station/admin': typeof StationAdminRoute
  '/station/verify': typeof StationVerifyRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/weather/closings': typeof WeatherClosingsRoute
  '/merch/': typeof MerchIndexRoute
  '/news/': typeof NewsIndexRoute
  '/_authenticated/account/licenses': typeof AuthenticatedAccountLicensesRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/_authenticated/admin/ai-log': typeof AuthenticatedAdminAiLogRoute
  '/_authenticated/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/closings': typeof AuthenticatedAdminClosingsRoute
  '/_authenticated/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRouteWithChildren
  '/_authenticated/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/_authenticated/admin/managed-sites': typeof AuthenticatedAdminManagedSitesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/merch': typeof AuthenticatedAdminMerchRoute
  '/_authenticated/admin/merch-settings': typeof AuthenticatedAdminMerchSettingsRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/_authenticated/admin/reddit': typeof AuthenticatedAdminRedditRouteWithChildren
  '/_authenticated/admin/reddit-automation': typeof AuthenticatedAdminRedditAutomationRoute
  '/_authenticated/admin/releases': typeof AuthenticatedAdminReleasesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/verdict': typeof AuthenticatedAdminVerdictRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/network_/$siteSlug/about': typeof NetworkSiteSlugAboutRoute
  '/network_/$siteSlug/admin': typeof NetworkSiteSlugAdminRoute
  '/network_/$siteSlug/contact': typeof NetworkSiteSlugContactRoute
  '/network_/$siteSlug/dmca': typeof NetworkSiteSlugDmcaRoute
  '/network_/$siteSlug/privacy': typeof NetworkSiteSlugPrivacyRoute
  '/network_/$siteSlug/shows': typeof NetworkSiteSlugShowsRoute
  '/network_/$siteSlug/sports': typeof NetworkSiteSlugSportsRoute
  '/network_/$siteSlug/terms': typeof NetworkSiteSlugTermsRoute
  '/network_/$siteSlug/watch-live': typeof NetworkSiteSlugWatchLiveRoute
  '/network_/$siteSlug/weather': typeof NetworkSiteSlugWeatherRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/network_/$siteSlug/': typeof NetworkSiteSlugIndexRoute
  '/_authenticated/admin/import/$batchId': typeof AuthenticatedAdminImportBatchIdRoute
  '/_authenticated/admin/network/health': typeof AuthenticatedAdminNetworkHealthRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/_authenticated/admin/reddit/$id': typeof AuthenticatedAdminRedditIdRoute
  '/api/public/hooks/backfill-comments': typeof ApiPublicHooksBackfillCommentsRoute
  '/api/public/hooks/manual-jsonl-import': typeof ApiPublicHooksManualJsonlImportRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/hooks/reddit-comment-callback': typeof ApiPublicHooksRedditCommentCallbackRoute
  '/api/public/hooks/reddit-comment-job': typeof ApiPublicHooksRedditCommentJobRoute
  '/api/public/hooks/reddit-listing-callback': typeof ApiPublicHooksRedditListingCallbackRoute
  '/api/public/hooks/reddit-listing-job': typeof ApiPublicHooksRedditListingJobRoute
  '/api/public/hooks/retry-merch': typeof ApiPublicHooksRetryMerchRoute
  '/api/public/hooks/verdict-ghost-tick': typeof ApiPublicHooksVerdictGhostTickRoute
  '/api/public/network/check-update': typeof ApiPublicNetworkCheckUpdateRoute
  '/api/public/network/ingest-release': typeof ApiPublicNetworkIngestReleaseRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/web-stories/$slug': typeof ApiPublicWebStoriesSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/network_/$siteSlug/news/$slug': typeof NetworkSiteSlugNewsSlugRoute
  '/_authenticated/account/managed-sites/': typeof AuthenticatedAccountManagedSitesIndexRoute
  '/network_/$siteSlug/news/': typeof NetworkSiteSlugNewsIndexRoute
  '/_authenticated/account/managed-sites/$siteId/onboarding': typeof AuthenticatedAccountManagedSitesSiteIdOnboardingRoute
  '/api/public/integrations/supabase/callback': typeof ApiPublicIntegrationsSupabaseCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/corrections-policy'
    | '/network'
    | '/news-sitemap.xml'
    | '/privacy-policy'
    | '/public-file'
    | '/robots.txt'
    | '/rss.xml'
    | '/shows'
    | '/sitemap.xml'
    | '/sports'
    | '/submit-news-tip'
    | '/terms-of-use'
    | '/unsubscribe'
    | '/watch-live'
    | '/weather'
    | '/admin'
    | '/api/media'
    | '/checkout/merch-return'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/merch/$id'
    | '/network/changelog'
    | '/network/docs'
    | '/network/stations'
    | '/network/$siteSlug'
    | '/news/$slug'
    | '/news/local'
    | '/station/admin'
    | '/station/verify'
    | '/stories/$slug'
    | '/weather/closings'
    | '/merch/'
    | '/news/'
    | '/account/licenses'
    | '/account/orders'
    | '/admin/abuse'
    | '/admin/ai-log'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/closings'
    | '/admin/comments'
    | '/admin/import'
    | '/admin/licenses'
    | '/admin/managed-sites'
    | '/admin/media'
    | '/admin/merch'
    | '/admin/merch-settings'
    | '/admin/posts'
    | '/admin/reddit'
    | '/admin/reddit-automation'
    | '/admin/releases'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/submissions'
    | '/admin/verdict'
    | '/lovable/email/suppression'
    | '/network/$siteSlug/about'
    | '/network/$siteSlug/admin'
    | '/network/$siteSlug/contact'
    | '/network/$siteSlug/dmca'
    | '/network/$siteSlug/privacy'
    | '/network/$siteSlug/shows'
    | '/network/$siteSlug/sports'
    | '/network/$siteSlug/terms'
    | '/network/$siteSlug/watch-live'
    | '/network/$siteSlug/weather'
    | '/admin/'
    | '/network/$siteSlug/'
    | '/admin/import/$batchId'
    | '/admin/network/health'
    | '/admin/posts/$id'
    | '/admin/reddit/$id'
    | '/api/public/hooks/backfill-comments'
    | '/api/public/hooks/manual-jsonl-import'
    | '/api/public/hooks/process-pending'
    | '/api/public/hooks/reddit-comment-callback'
    | '/api/public/hooks/reddit-comment-job'
    | '/api/public/hooks/reddit-listing-callback'
    | '/api/public/hooks/reddit-listing-job'
    | '/api/public/hooks/retry-merch'
    | '/api/public/hooks/verdict-ghost-tick'
    | '/api/public/network/check-update'
    | '/api/public/network/ingest-release'
    | '/api/public/payments/webhook'
    | '/api/public/web-stories/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/network/$siteSlug/news/$slug'
    | '/account/managed-sites/'
    | '/network/$siteSlug/news/'
    | '/account/managed-sites/$siteId/onboarding'
    | '/api/public/integrations/supabase/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/corrections-policy'
    | '/network'
    | '/news-sitemap.xml'
    | '/privacy-policy'
    | '/public-file'
    | '/robots.txt'
    | '/rss.xml'
    | '/shows'
    | '/sitemap.xml'
    | '/sports'
    | '/submit-news-tip'
    | '/terms-of-use'
    | '/unsubscribe'
    | '/watch-live'
    | '/weather'
    | '/api/media'
    | '/checkout/merch-return'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/merch/$id'
    | '/network/changelog'
    | '/network/docs'
    | '/network/stations'
    | '/news/$slug'
    | '/news/local'
    | '/station/admin'
    | '/station/verify'
    | '/stories/$slug'
    | '/weather/closings'
    | '/merch'
    | '/news'
    | '/account/licenses'
    | '/account/orders'
    | '/admin/abuse'
    | '/admin/ai-log'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/closings'
    | '/admin/comments'
    | '/admin/import'
    | '/admin/licenses'
    | '/admin/managed-sites'
    | '/admin/media'
    | '/admin/merch'
    | '/admin/merch-settings'
    | '/admin/posts'
    | '/admin/reddit'
    | '/admin/reddit-automation'
    | '/admin/releases'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/submissions'
    | '/admin/verdict'
    | '/lovable/email/suppression'
    | '/network/$siteSlug/about'
    | '/network/$siteSlug/admin'
    | '/network/$siteSlug/contact'
    | '/network/$siteSlug/dmca'
    | '/network/$siteSlug/privacy'
    | '/network/$siteSlug/shows'
    | '/network/$siteSlug/sports'
    | '/network/$siteSlug/terms'
    | '/network/$siteSlug/watch-live'
    | '/network/$siteSlug/weather'
    | '/admin'
    | '/network/$siteSlug'
    | '/admin/import/$batchId'
    | '/admin/network/health'
    | '/admin/posts/$id'
    | '/admin/reddit/$id'
    | '/api/public/hooks/backfill-comments'
    | '/api/public/hooks/manual-jsonl-import'
    | '/api/public/hooks/process-pending'
    | '/api/public/hooks/reddit-comment-callback'
    | '/api/public/hooks/reddit-comment-job'
    | '/api/public/hooks/reddit-listing-callback'
    | '/api/public/hooks/reddit-listing-job'
    | '/api/public/hooks/retry-merch'
    | '/api/public/hooks/verdict-ghost-tick'
    | '/api/public/network/check-update'
    | '/api/public/network/ingest-release'
    | '/api/public/payments/webhook'
    | '/api/public/web-stories/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/network/$siteSlug/news/$slug'
    | '/account/managed-sites'
    | '/network/$siteSlug/news'
    | '/account/managed-sites/$siteId/onboarding'
    | '/api/public/integrations/supabase/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/corrections-policy'
    | '/network'
    | '/news-sitemap.xml'
    | '/privacy-policy'
    | '/public-file'
    | '/robots.txt'
    | '/rss.xml'
    | '/shows'
    | '/sitemap.xml'
    | '/sports'
    | '/submit-news-tip'
    | '/terms-of-use'
    | '/unsubscribe'
    | '/watch-live'
    | '/weather'
    | '/_authenticated/admin'
    | '/api/media'
    | '/checkout/merch-return'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/merch/$id'
    | '/network/changelog'
    | '/network/docs'
    | '/network/stations'
    | '/network_/$siteSlug'
    | '/news/$slug'
    | '/news/local'
    | '/station/admin'
    | '/station/verify'
    | '/stories/$slug'
    | '/weather/closings'
    | '/merch/'
    | '/news/'
    | '/_authenticated/account/licenses'
    | '/_authenticated/account/orders'
    | '/_authenticated/admin/abuse'
    | '/_authenticated/admin/ai-log'
    | '/_authenticated/admin/authors'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/closings'
    | '/_authenticated/admin/comments'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/licenses'
    | '/_authenticated/admin/managed-sites'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/merch'
    | '/_authenticated/admin/merch-settings'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/reddit'
    | '/_authenticated/admin/reddit-automation'
    | '/_authenticated/admin/releases'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/site-content'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/verdict'
    | '/lovable/email/suppression'
    | '/network_/$siteSlug/about'
    | '/network_/$siteSlug/admin'
    | '/network_/$siteSlug/contact'
    | '/network_/$siteSlug/dmca'
    | '/network_/$siteSlug/privacy'
    | '/network_/$siteSlug/shows'
    | '/network_/$siteSlug/sports'
    | '/network_/$siteSlug/terms'
    | '/network_/$siteSlug/watch-live'
    | '/network_/$siteSlug/weather'
    | '/_authenticated/admin/'
    | '/network_/$siteSlug/'
    | '/_authenticated/admin/import/$batchId'
    | '/_authenticated/admin/network/health'
    | '/_authenticated/admin/posts/$id'
    | '/_authenticated/admin/reddit/$id'
    | '/api/public/hooks/backfill-comments'
    | '/api/public/hooks/manual-jsonl-import'
    | '/api/public/hooks/process-pending'
    | '/api/public/hooks/reddit-comment-callback'
    | '/api/public/hooks/reddit-comment-job'
    | '/api/public/hooks/reddit-listing-callback'
    | '/api/public/hooks/reddit-listing-job'
    | '/api/public/hooks/retry-merch'
    | '/api/public/hooks/verdict-ghost-tick'
    | '/api/public/network/check-update'
    | '/api/public/network/ingest-release'
    | '/api/public/payments/webhook'
    | '/api/public/web-stories/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/network_/$siteSlug/news/$slug'
    | '/_authenticated/account/managed-sites/'
    | '/network_/$siteSlug/news/'
    | '/_authenticated/account/managed-sites/$siteId/onboarding'
    | '/api/public/integrations/supabase/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CorrectionsPolicyRoute: typeof CorrectionsPolicyRoute
  NetworkRoute: typeof NetworkRouteWithChildren
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PublicFileRoute: typeof PublicFileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  ShowsRoute: typeof ShowsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  SubmitNewsTipRoute: typeof SubmitNewsTipRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WatchLiveRoute: typeof WatchLiveRoute
  WeatherRoute: typeof WeatherRouteWithChildren
  ApiMediaRoute: typeof ApiMediaRoute
  CheckoutMerchReturnRoute: typeof CheckoutMerchReturnRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  MerchIdRoute: typeof MerchIdRoute
  NetworkSiteSlugRoute: typeof NetworkSiteSlugRouteWithChildren
  NewsSlugRoute: typeof NewsSlugRoute
  NewsLocalRoute: typeof NewsLocalRoute
  StationAdminRoute: typeof StationAdminRoute
  StationVerifyRoute: typeof StationVerifyRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  MerchIndexRoute: typeof MerchIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksBackfillCommentsRoute: typeof ApiPublicHooksBackfillCommentsRoute
  ApiPublicHooksManualJsonlImportRoute: typeof ApiPublicHooksManualJsonlImportRoute
  ApiPublicHooksProcessPendingRoute: typeof ApiPublicHooksProcessPendingRoute
  ApiPublicHooksRedditCommentCallbackRoute: typeof ApiPublicHooksRedditCommentCallbackRoute
  ApiPublicHooksRedditCommentJobRoute: typeof ApiPublicHooksRedditCommentJobRoute
  ApiPublicHooksRedditListingCallbackRoute: typeof ApiPublicHooksRedditListingCallbackRoute
  ApiPublicHooksRedditListingJobRoute: typeof ApiPublicHooksRedditListingJobRoute
  ApiPublicHooksRetryMerchRoute: typeof ApiPublicHooksRetryMerchRoute
  ApiPublicHooksVerdictGhostTickRoute: typeof ApiPublicHooksVerdictGhostTickRoute
  ApiPublicNetworkCheckUpdateRoute: typeof ApiPublicNetworkCheckUpdateRoute
  ApiPublicNetworkIngestReleaseRoute: typeof ApiPublicNetworkIngestReleaseRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWebStoriesSlugRoute: typeof ApiPublicWebStoriesSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicIntegrationsSupabaseCallbackRoute: typeof ApiPublicIntegrationsSupabaseCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-live': {
      id: '/watch-live'
      path: '/watch-live'
      fullPath: '/watch-live'
      preLoaderRoute: typeof WatchLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-news-tip': {
      id: '/submit-news-tip'
      path: '/submit-news-tip'
      fullPath: '/submit-news-tip'
      preLoaderRoute: typeof SubmitNewsTipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-file': {
      id: '/public-file'
      path: '/public-file'
      fullPath: '/public-file'
      preLoaderRoute: typeof PublicFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections-policy': {
      id: '/corrections-policy'
      path: '/corrections-policy'
      fullPath: '/corrections-policy'
      preLoaderRoute: typeof CorrectionsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/': {
      id: '/merch/'
      path: '/merch'
      fullPath: '/merch/'
      preLoaderRoute: typeof MerchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/closings': {
      id: '/weather/closings'
      path: '/closings'
      fullPath: '/weather/closings'
      preLoaderRoute: typeof WeatherClosingsRouteImport
      parentRoute: typeof WeatherRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/verify': {
      id: '/station/verify'
      path: '/station/verify'
      fullPath: '/station/verify'
      preLoaderRoute: typeof StationVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/admin': {
      id: '/station/admin'
      path: '/station/admin'
      fullPath: '/station/admin'
      preLoaderRoute: typeof StationAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/local': {
      id: '/news/local'
      path: '/news/local'
      fullPath: '/news/local'
      preLoaderRoute: typeof NewsLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network_/$siteSlug': {
      id: '/network_/$siteSlug'
      path: '/network/$siteSlug'
      fullPath: '/network/$siteSlug'
      preLoaderRoute: typeof NetworkSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/stations': {
      id: '/network/stations'
      path: '/stations'
      fullPath: '/network/stations'
      preLoaderRoute: typeof NetworkStationsRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/network/docs': {
      id: '/network/docs'
      path: '/docs'
      fullPath: '/network/docs'
      preLoaderRoute: typeof NetworkDocsRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/network/changelog': {
      id: '/network/changelog'
      path: '/changelog'
      fullPath: '/network/changelog'
      preLoaderRoute: typeof NetworkChangelogRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/merch/$id': {
      id: '/merch/$id'
      path: '/merch/$id'
      fullPath: '/merch/$id'
      preLoaderRoute: typeof MerchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/merch-return': {
      id: '/checkout/merch-return'
      path: '/checkout/merch-return'
      fullPath: '/checkout/merch-return'
      preLoaderRoute: typeof CheckoutMerchReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/network_/$siteSlug/': {
      id: '/network_/$siteSlug/'
      path: '/'
      fullPath: '/network/$siteSlug/'
      preLoaderRoute: typeof NetworkSiteSlugIndexRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/network_/$siteSlug/weather': {
      id: '/network_/$siteSlug/weather'
      path: '/weather'
      fullPath: '/network/$siteSlug/weather'
      preLoaderRoute: typeof NetworkSiteSlugWeatherRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/watch-live': {
      id: '/network_/$siteSlug/watch-live'
      path: '/watch-live'
      fullPath: '/network/$siteSlug/watch-live'
      preLoaderRoute: typeof NetworkSiteSlugWatchLiveRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/terms': {
      id: '/network_/$siteSlug/terms'
      path: '/terms'
      fullPath: '/network/$siteSlug/terms'
      preLoaderRoute: typeof NetworkSiteSlugTermsRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/sports': {
      id: '/network_/$siteSlug/sports'
      path: '/sports'
      fullPath: '/network/$siteSlug/sports'
      preLoaderRoute: typeof NetworkSiteSlugSportsRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/shows': {
      id: '/network_/$siteSlug/shows'
      path: '/shows'
      fullPath: '/network/$siteSlug/shows'
      preLoaderRoute: typeof NetworkSiteSlugShowsRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/privacy': {
      id: '/network_/$siteSlug/privacy'
      path: '/privacy'
      fullPath: '/network/$siteSlug/privacy'
      preLoaderRoute: typeof NetworkSiteSlugPrivacyRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/dmca': {
      id: '/network_/$siteSlug/dmca'
      path: '/dmca'
      fullPath: '/network/$siteSlug/dmca'
      preLoaderRoute: typeof NetworkSiteSlugDmcaRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/contact': {
      id: '/network_/$siteSlug/contact'
      path: '/contact'
      fullPath: '/network/$siteSlug/contact'
      preLoaderRoute: typeof NetworkSiteSlugContactRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/admin': {
      id: '/network_/$siteSlug/admin'
      path: '/admin'
      fullPath: '/network/$siteSlug/admin'
      preLoaderRoute: typeof NetworkSiteSlugAdminRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/network_/$siteSlug/about': {
      id: '/network_/$siteSlug/about'
      path: '/about'
      fullPath: '/network/$siteSlug/about'
      preLoaderRoute: typeof NetworkSiteSlugAboutRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/verdict': {
      id: '/_authenticated/admin/verdict'
      path: '/verdict'
      fullPath: '/admin/verdict'
      preLoaderRoute: typeof AuthenticatedAdminVerdictRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/site-content': {
      id: '/_authenticated/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AuthenticatedAdminSiteContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/releases': {
      id: '/_authenticated/admin/releases'
      path: '/releases'
      fullPath: '/admin/releases'
      preLoaderRoute: typeof AuthenticatedAdminReleasesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reddit-automation': {
      id: '/_authenticated/admin/reddit-automation'
      path: '/reddit-automation'
      fullPath: '/admin/reddit-automation'
      preLoaderRoute: typeof AuthenticatedAdminRedditAutomationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reddit': {
      id: '/_authenticated/admin/reddit'
      path: '/reddit'
      fullPath: '/admin/reddit'
      preLoaderRoute: typeof AuthenticatedAdminRedditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/merch-settings': {
      id: '/_authenticated/admin/merch-settings'
      path: '/merch-settings'
      fullPath: '/admin/merch-settings'
      preLoaderRoute: typeof AuthenticatedAdminMerchSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/merch': {
      id: '/_authenticated/admin/merch'
      path: '/merch'
      fullPath: '/admin/merch'
      preLoaderRoute: typeof AuthenticatedAdminMerchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/managed-sites': {
      id: '/_authenticated/admin/managed-sites'
      path: '/managed-sites'
      fullPath: '/admin/managed-sites'
      preLoaderRoute: typeof AuthenticatedAdminManagedSitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/licenses': {
      id: '/_authenticated/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AuthenticatedAdminLicensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comments': {
      id: '/_authenticated/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/closings': {
      id: '/_authenticated/admin/closings'
      path: '/closings'
      fullPath: '/admin/closings'
      preLoaderRoute: typeof AuthenticatedAdminClosingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/authors': {
      id: '/_authenticated/admin/authors'
      path: '/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AuthenticatedAdminAuthorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-log': {
      id: '/_authenticated/admin/ai-log'
      path: '/ai-log'
      fullPath: '/admin/ai-log'
      preLoaderRoute: typeof AuthenticatedAdminAiLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/abuse': {
      id: '/_authenticated/admin/abuse'
      path: '/abuse'
      fullPath: '/admin/abuse'
      preLoaderRoute: typeof AuthenticatedAdminAbuseRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/licenses': {
      id: '/_authenticated/account/licenses'
      path: '/account/licenses'
      fullPath: '/account/licenses'
      preLoaderRoute: typeof AuthenticatedAccountLicensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/network_/$siteSlug/news/': {
      id: '/network_/$siteSlug/news/'
      path: '/news'
      fullPath: '/network/$siteSlug/news/'
      preLoaderRoute: typeof NetworkSiteSlugNewsIndexRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/_authenticated/account/managed-sites/': {
      id: '/_authenticated/account/managed-sites/'
      path: '/account/managed-sites'
      fullPath: '/account/managed-sites/'
      preLoaderRoute: typeof AuthenticatedAccountManagedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/network_/$siteSlug/news/$slug': {
      id: '/network_/$siteSlug/news/$slug'
      path: '/news/$slug'
      fullPath: '/network/$siteSlug/news/$slug'
      preLoaderRoute: typeof NetworkSiteSlugNewsSlugRouteImport
      parentRoute: typeof NetworkSiteSlugRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/web-stories/$slug': {
      id: '/api/public/web-stories/$slug'
      path: '/api/public/web-stories/$slug'
      fullPath: '/api/public/web-stories/$slug'
      preLoaderRoute: typeof ApiPublicWebStoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/network/ingest-release': {
      id: '/api/public/network/ingest-release'
      path: '/api/public/network/ingest-release'
      fullPath: '/api/public/network/ingest-release'
      preLoaderRoute: typeof ApiPublicNetworkIngestReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/network/check-update': {
      id: '/api/public/network/check-update'
      path: '/api/public/network/check-update'
      fullPath: '/api/public/network/check-update'
      preLoaderRoute: typeof ApiPublicNetworkCheckUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verdict-ghost-tick': {
      id: '/api/public/hooks/verdict-ghost-tick'
      path: '/api/public/hooks/verdict-ghost-tick'
      fullPath: '/api/public/hooks/verdict-ghost-tick'
      preLoaderRoute: typeof ApiPublicHooksVerdictGhostTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retry-merch': {
      id: '/api/public/hooks/retry-merch'
      path: '/api/public/hooks/retry-merch'
      fullPath: '/api/public/hooks/retry-merch'
      preLoaderRoute: typeof ApiPublicHooksRetryMerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reddit-listing-job': {
      id: '/api/public/hooks/reddit-listing-job'
      path: '/api/public/hooks/reddit-listing-job'
      fullPath: '/api/public/hooks/reddit-listing-job'
      preLoaderRoute: typeof ApiPublicHooksRedditListingJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reddit-listing-callback': {
      id: '/api/public/hooks/reddit-listing-callback'
      path: '/api/public/hooks/reddit-listing-callback'
      fullPath: '/api/public/hooks/reddit-listing-callback'
      preLoaderRoute: typeof ApiPublicHooksRedditListingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reddit-comment-job': {
      id: '/api/public/hooks/reddit-comment-job'
      path: '/api/public/hooks/reddit-comment-job'
      fullPath: '/api/public/hooks/reddit-comment-job'
      preLoaderRoute: typeof ApiPublicHooksRedditCommentJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reddit-comment-callback': {
      id: '/api/public/hooks/reddit-comment-callback'
      path: '/api/public/hooks/reddit-comment-callback'
      fullPath: '/api/public/hooks/reddit-comment-callback'
      preLoaderRoute: typeof ApiPublicHooksRedditCommentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-pending': {
      id: '/api/public/hooks/process-pending'
      path: '/api/public/hooks/process-pending'
      fullPath: '/api/public/hooks/process-pending'
      preLoaderRoute: typeof ApiPublicHooksProcessPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/manual-jsonl-import': {
      id: '/api/public/hooks/manual-jsonl-import'
      path: '/api/public/hooks/manual-jsonl-import'
      fullPath: '/api/public/hooks/manual-jsonl-import'
      preLoaderRoute: typeof ApiPublicHooksManualJsonlImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-comments': {
      id: '/api/public/hooks/backfill-comments'
      path: '/api/public/hooks/backfill-comments'
      fullPath: '/api/public/hooks/backfill-comments'
      preLoaderRoute: typeof ApiPublicHooksBackfillCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reddit/$id': {
      id: '/_authenticated/admin/reddit/$id'
      path: '/$id'
      fullPath: '/admin/reddit/$id'
      preLoaderRoute: typeof AuthenticatedAdminRedditIdRouteImport
      parentRoute: typeof AuthenticatedAdminRedditRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedAdminPostsRoute
    }
    '/_authenticated/admin/network/health': {
      id: '/_authenticated/admin/network/health'
      path: '/network/health'
      fullPath: '/admin/network/health'
      preLoaderRoute: typeof AuthenticatedAdminNetworkHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import/$batchId': {
      id: '/_authenticated/admin/import/$batchId'
      path: '/$batchId'
      fullPath: '/admin/import/$batchId'
      preLoaderRoute: typeof AuthenticatedAdminImportBatchIdRouteImport
      parentRoute: typeof AuthenticatedAdminImportRoute
    }
    '/api/public/integrations/supabase/callback': {
      id: '/api/public/integrations/supabase/callback'
      path: '/api/public/integrations/supabase/callback'
      fullPath: '/api/public/integrations/supabase/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsSupabaseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/managed-sites/$siteId/onboarding': {
      id: '/_authenticated/account/managed-sites/$siteId/onboarding'
      path: '/account/managed-sites/$siteId/onboarding'
      fullPath: '/account/managed-sites/$siteId/onboarding'
      preLoaderRoute: typeof AuthenticatedAccountManagedSitesSiteIdOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminImportRouteChildren {
  AuthenticatedAdminImportBatchIdRoute: typeof AuthenticatedAdminImportBatchIdRoute
}

const AuthenticatedAdminImportRouteChildren: AuthenticatedAdminImportRouteChildren =
  {
    AuthenticatedAdminImportBatchIdRoute: AuthenticatedAdminImportBatchIdRoute,
  }

const AuthenticatedAdminImportRouteWithChildren =
  AuthenticatedAdminImportRoute._addFileChildren(
    AuthenticatedAdminImportRouteChildren,
  )

interface AuthenticatedAdminPostsRouteChildren {
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
}

const AuthenticatedAdminPostsRouteChildren: AuthenticatedAdminPostsRouteChildren =
  {
    AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
  }

const AuthenticatedAdminPostsRouteWithChildren =
  AuthenticatedAdminPostsRoute._addFileChildren(
    AuthenticatedAdminPostsRouteChildren,
  )

interface AuthenticatedAdminRedditRouteChildren {
  AuthenticatedAdminRedditIdRoute: typeof AuthenticatedAdminRedditIdRoute
}

const AuthenticatedAdminRedditRouteChildren: AuthenticatedAdminRedditRouteChildren =
  {
    AuthenticatedAdminRedditIdRoute: AuthenticatedAdminRedditIdRoute,
  }

const AuthenticatedAdminRedditRouteWithChildren =
  AuthenticatedAdminRedditRoute._addFileChildren(
    AuthenticatedAdminRedditRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAbuseRoute: typeof AuthenticatedAdminAbuseRoute
  AuthenticatedAdminAiLogRoute: typeof AuthenticatedAdminAiLogRoute
  AuthenticatedAdminAuthorsRoute: typeof AuthenticatedAdminAuthorsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminClosingsRoute: typeof AuthenticatedAdminClosingsRoute
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRouteWithChildren
  AuthenticatedAdminLicensesRoute: typeof AuthenticatedAdminLicensesRoute
  AuthenticatedAdminManagedSitesRoute: typeof AuthenticatedAdminManagedSitesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMerchRoute: typeof AuthenticatedAdminMerchRoute
  AuthenticatedAdminMerchSettingsRoute: typeof AuthenticatedAdminMerchSettingsRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRouteWithChildren
  AuthenticatedAdminRedditRoute: typeof AuthenticatedAdminRedditRouteWithChildren
  AuthenticatedAdminRedditAutomationRoute: typeof AuthenticatedAdminRedditAutomationRoute
  AuthenticatedAdminReleasesRoute: typeof AuthenticatedAdminReleasesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSiteContentRoute: typeof AuthenticatedAdminSiteContentRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminVerdictRoute: typeof AuthenticatedAdminVerdictRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminNetworkHealthRoute: typeof AuthenticatedAdminNetworkHealthRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAbuseRoute: AuthenticatedAdminAbuseRoute,
  AuthenticatedAdminAiLogRoute: AuthenticatedAdminAiLogRoute,
  AuthenticatedAdminAuthorsRoute: AuthenticatedAdminAuthorsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminClosingsRoute: AuthenticatedAdminClosingsRoute,
  AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRouteWithChildren,
  AuthenticatedAdminLicensesRoute: AuthenticatedAdminLicensesRoute,
  AuthenticatedAdminManagedSitesRoute: AuthenticatedAdminManagedSitesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMerchRoute: AuthenticatedAdminMerchRoute,
  AuthenticatedAdminMerchSettingsRoute: AuthenticatedAdminMerchSettingsRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRouteWithChildren,
  AuthenticatedAdminRedditRoute: AuthenticatedAdminRedditRouteWithChildren,
  AuthenticatedAdminRedditAutomationRoute:
    AuthenticatedAdminRedditAutomationRoute,
  AuthenticatedAdminReleasesRoute: AuthenticatedAdminReleasesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSiteContentRoute: AuthenticatedAdminSiteContentRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminVerdictRoute: AuthenticatedAdminVerdictRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminNetworkHealthRoute: AuthenticatedAdminNetworkHealthRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAccountLicensesRoute: typeof AuthenticatedAccountLicensesRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountManagedSitesIndexRoute: typeof AuthenticatedAccountManagedSitesIndexRoute
  AuthenticatedAccountManagedSitesSiteIdOnboardingRoute: typeof AuthenticatedAccountManagedSitesSiteIdOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAccountLicensesRoute: AuthenticatedAccountLicensesRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountManagedSitesIndexRoute:
    AuthenticatedAccountManagedSitesIndexRoute,
  AuthenticatedAccountManagedSitesSiteIdOnboardingRoute:
    AuthenticatedAccountManagedSitesSiteIdOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NetworkRouteChildren {
  NetworkChangelogRoute: typeof NetworkChangelogRoute
  NetworkDocsRoute: typeof NetworkDocsRoute
  NetworkStationsRoute: typeof NetworkStationsRoute
}

const NetworkRouteChildren: NetworkRouteChildren = {
  NetworkChangelogRoute: NetworkChangelogRoute,
  NetworkDocsRoute: NetworkDocsRoute,
  NetworkStationsRoute: NetworkStationsRoute,
}

const NetworkRouteWithChildren =
  NetworkRoute._addFileChildren(NetworkRouteChildren)

interface WeatherRouteChildren {
  WeatherClosingsRoute: typeof WeatherClosingsRoute
}

const WeatherRouteChildren: WeatherRouteChildren = {
  WeatherClosingsRoute: WeatherClosingsRoute,
}

const WeatherRouteWithChildren =
  WeatherRoute._addFileChildren(WeatherRouteChildren)

interface NetworkSiteSlugRouteChildren {
  NetworkSiteSlugAboutRoute: typeof NetworkSiteSlugAboutRoute
  NetworkSiteSlugAdminRoute: typeof NetworkSiteSlugAdminRoute
  NetworkSiteSlugContactRoute: typeof NetworkSiteSlugContactRoute
  NetworkSiteSlugDmcaRoute: typeof NetworkSiteSlugDmcaRoute
  NetworkSiteSlugPrivacyRoute: typeof NetworkSiteSlugPrivacyRoute
  NetworkSiteSlugShowsRoute: typeof NetworkSiteSlugShowsRoute
  NetworkSiteSlugSportsRoute: typeof NetworkSiteSlugSportsRoute
  NetworkSiteSlugTermsRoute: typeof NetworkSiteSlugTermsRoute
  NetworkSiteSlugWatchLiveRoute: typeof NetworkSiteSlugWatchLiveRoute
  NetworkSiteSlugWeatherRoute: typeof NetworkSiteSlugWeatherRoute
  NetworkSiteSlugIndexRoute: typeof NetworkSiteSlugIndexRoute
  NetworkSiteSlugNewsSlugRoute: typeof NetworkSiteSlugNewsSlugRoute
  NetworkSiteSlugNewsIndexRoute: typeof NetworkSiteSlugNewsIndexRoute
}

const NetworkSiteSlugRouteChildren: NetworkSiteSlugRouteChildren = {
  NetworkSiteSlugAboutRoute: NetworkSiteSlugAboutRoute,
  NetworkSiteSlugAdminRoute: NetworkSiteSlugAdminRoute,
  NetworkSiteSlugContactRoute: NetworkSiteSlugContactRoute,
  NetworkSiteSlugDmcaRoute: NetworkSiteSlugDmcaRoute,
  NetworkSiteSlugPrivacyRoute: NetworkSiteSlugPrivacyRoute,
  NetworkSiteSlugShowsRoute: NetworkSiteSlugShowsRoute,
  NetworkSiteSlugSportsRoute: NetworkSiteSlugSportsRoute,
  NetworkSiteSlugTermsRoute: NetworkSiteSlugTermsRoute,
  NetworkSiteSlugWatchLiveRoute: NetworkSiteSlugWatchLiveRoute,
  NetworkSiteSlugWeatherRoute: NetworkSiteSlugWeatherRoute,
  NetworkSiteSlugIndexRoute: NetworkSiteSlugIndexRoute,
  NetworkSiteSlugNewsSlugRoute: NetworkSiteSlugNewsSlugRoute,
  NetworkSiteSlugNewsIndexRoute: NetworkSiteSlugNewsIndexRoute,
}

const NetworkSiteSlugRouteWithChildren = NetworkSiteSlugRoute._addFileChildren(
  NetworkSiteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdvertiseRoute: AdvertiseRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CorrectionsPolicyRoute: CorrectionsPolicyRoute,
  NetworkRoute: NetworkRouteWithChildren,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PublicFileRoute: PublicFileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  ShowsRoute: ShowsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  SubmitNewsTipRoute: SubmitNewsTipRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WatchLiveRoute: WatchLiveRoute,
  WeatherRoute: WeatherRouteWithChildren,
  ApiMediaRoute: ApiMediaRoute,
  CheckoutMerchReturnRoute: CheckoutMerchReturnRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  MerchIdRoute: MerchIdRoute,
  NetworkSiteSlugRoute: NetworkSiteSlugRouteWithChildren,
  NewsSlugRoute: NewsSlugRoute,
  NewsLocalRoute: NewsLocalRoute,
  StationAdminRoute: StationAdminRoute,
  StationVerifyRoute: StationVerifyRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  MerchIndexRoute: MerchIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksBackfillCommentsRoute: ApiPublicHooksBackfillCommentsRoute,
  ApiPublicHooksManualJsonlImportRoute: ApiPublicHooksManualJsonlImportRoute,
  ApiPublicHooksProcessPendingRoute: ApiPublicHooksProcessPendingRoute,
  ApiPublicHooksRedditCommentCallbackRoute:
    ApiPublicHooksRedditCommentCallbackRoute,
  ApiPublicHooksRedditCommentJobRoute: ApiPublicHooksRedditCommentJobRoute,
  ApiPublicHooksRedditListingCallbackRoute:
    ApiPublicHooksRedditListingCallbackRoute,
  ApiPublicHooksRedditListingJobRoute: ApiPublicHooksRedditListingJobRoute,
  ApiPublicHooksRetryMerchRoute: ApiPublicHooksRetryMerchRoute,
  ApiPublicHooksVerdictGhostTickRoute: ApiPublicHooksVerdictGhostTickRoute,
  ApiPublicNetworkCheckUpdateRoute: ApiPublicNetworkCheckUpdateRoute,
  ApiPublicNetworkIngestReleaseRoute: ApiPublicNetworkIngestReleaseRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWebStoriesSlugRoute: ApiPublicWebStoriesSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicIntegrationsSupabaseCallbackRoute:
    ApiPublicIntegrationsSupabaseCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
