/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WatchLiveRouteImport } from './routes/watch-live'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SubmitNewsTipRouteImport } from './routes/submit-news-tip'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PublicFileRouteImport } from './routes/public-file'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as CorrectionsPolicyRouteImport } from './routes/corrections-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsLocalRouteImport } from './routes/news.local'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRedditRouteImport } from './routes/_authenticated/admin.reddit'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminCommentsRouteImport } from './routes/_authenticated/admin.comments'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminAuthorsRouteImport } from './routes/_authenticated/admin.authors'
import { Route as AuthenticatedAdminAiLogRouteImport } from './routes/_authenticated/admin.ai-log'
import { Route as ApiPublicHooksProcessPendingRouteImport } from './routes/api/public/hooks/process-pending'
import { Route as AuthenticatedAdminRedditIdRouteImport } from './routes/_authenticated/admin.reddit.$id'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin.posts.$id'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLiveRoute = WatchLiveRouteImport.update({
  id: '/watch-live',
  path: '/watch-live',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitNewsTipRoute = SubmitNewsTipRouteImport.update({
  id: '/submit-news-tip',
  path: '/submit-news-tip',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicFileRoute = PublicFileRouteImport.update({
  id: '/public-file',
  path: '/public-file',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsPolicyRoute = CorrectionsPolicyRouteImport.update({
  id: '/corrections-policy',
  path: '/corrections-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsLocalRoute = NewsLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRedditRoute =
  AuthenticatedAdminRedditRouteImport.update({
    id: '/reddit',
    path: '/reddit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuthorsRoute =
  AuthenticatedAdminAuthorsRouteImport.update({
    id: '/authors',
    path: '/authors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiLogRoute = AuthenticatedAdminAiLogRouteImport.update({
  id: '/ai-log',
  path: '/ai-log',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHooksProcessPendingRoute =
  ApiPublicHooksProcessPendingRouteImport.update({
    id: '/api/public/hooks/process-pending',
    path: '/api/public/hooks/process-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRedditIdRoute =
  AuthenticatedAdminRedditIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRedditRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPostsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-file': typeof PublicFileRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/submit-news-tip': typeof SubmitNewsTipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/local': typeof NewsLocalRoute
  '/admin/ai-log': typeof AuthenticatedAdminAiLogRoute
  '/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/admin/reddit': typeof AuthenticatedAdminRedditRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/reddit/$id': typeof AuthenticatedAdminRedditIdRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-file': typeof PublicFileRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/submit-news-tip': typeof SubmitNewsTipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRoute
  '/api/media': typeof ApiMediaRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/local': typeof NewsLocalRoute
  '/admin/ai-log': typeof AuthenticatedAdminAiLogRoute
  '/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/admin/reddit': typeof AuthenticatedAdminRedditRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/reddit/$id': typeof AuthenticatedAdminRedditIdRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-file': typeof PublicFileRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/submit-news-tip': typeof SubmitNewsTipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/local': typeof NewsLocalRoute
  '/_authenticated/admin/ai-log': typeof AuthenticatedAdminAiLogRoute
  '/_authenticated/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/_authenticated/admin/reddit': typeof AuthenticatedAdminRedditRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/_authenticated/admin/reddit/$id': typeof AuthenticatedAdminRedditIdRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/corrections-policy'
    | '/news'
    | '/privacy-policy'
    | '/public-file'
    | '/rss.xml'
    | '/shows'
    | '/sitemap.xml'
    | '/sports'
    | '/submit-news-tip'
    | '/terms-of-use'
    | '/watch-live'
    | '/weather'
    | '/admin'
    | '/api/media'
    | '/news/$slug'
    | '/news/local'
    | '/admin/ai-log'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/import'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/reddit'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/reddit/$id'
    | '/api/public/hooks/process-pending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/corrections-policy'
    | '/news'
    | '/privacy-policy'
    | '/public-file'
    | '/rss.xml'
    | '/shows'
    | '/sitemap.xml'
    | '/sports'
    | '/submit-news-tip'
    | '/terms-of-use'
    | '/watch-live'
    | '/weather'
    | '/api/media'
    | '/news/$slug'
    | '/news/local'
    | '/admin/ai-log'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/import'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/reddit'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin'
    | '/admin/posts/$id'
    | '/admin/reddit/$id'
    | '/api/public/hooks/process-pending'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/corrections-policy'
    | '/news'
    | '/privacy-policy'
    | '/public-file'
    | '/rss.xml'
    | '/shows'
    | '/sitemap.xml'
    | '/sports'
    | '/submit-news-tip'
    | '/terms-of-use'
    | '/watch-live'
    | '/weather'
    | '/_authenticated/admin'
    | '/api/media'
    | '/news/$slug'
    | '/news/local'
    | '/_authenticated/admin/ai-log'
    | '/_authenticated/admin/authors'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/comments'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/reddit'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/posts/$id'
    | '/_authenticated/admin/reddit/$id'
    | '/api/public/hooks/process-pending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CorrectionsPolicyRoute: typeof CorrectionsPolicyRoute
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PublicFileRoute: typeof PublicFileRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  ShowsRoute: typeof ShowsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  SubmitNewsTipRoute: typeof SubmitNewsTipRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  WatchLiveRoute: typeof WatchLiveRoute
  WeatherRoute: typeof WeatherRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiPublicHooksProcessPendingRoute: typeof ApiPublicHooksProcessPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-live': {
      id: '/watch-live'
      path: '/watch-live'
      fullPath: '/watch-live'
      preLoaderRoute: typeof WatchLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-news-tip': {
      id: '/submit-news-tip'
      path: '/submit-news-tip'
      fullPath: '/submit-news-tip'
      preLoaderRoute: typeof SubmitNewsTipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-file': {
      id: '/public-file'
      path: '/public-file'
      fullPath: '/public-file'
      preLoaderRoute: typeof PublicFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections-policy': {
      id: '/corrections-policy'
      path: '/corrections-policy'
      fullPath: '/corrections-policy'
      preLoaderRoute: typeof CorrectionsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/local': {
      id: '/news/local'
      path: '/local'
      fullPath: '/news/local'
      preLoaderRoute: typeof NewsLocalRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reddit': {
      id: '/_authenticated/admin/reddit'
      path: '/reddit'
      fullPath: '/admin/reddit'
      preLoaderRoute: typeof AuthenticatedAdminRedditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comments': {
      id: '/_authenticated/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/authors': {
      id: '/_authenticated/admin/authors'
      path: '/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AuthenticatedAdminAuthorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-log': {
      id: '/_authenticated/admin/ai-log'
      path: '/ai-log'
      fullPath: '/admin/ai-log'
      preLoaderRoute: typeof AuthenticatedAdminAiLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/process-pending': {
      id: '/api/public/hooks/process-pending'
      path: '/api/public/hooks/process-pending'
      fullPath: '/api/public/hooks/process-pending'
      preLoaderRoute: typeof ApiPublicHooksProcessPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reddit/$id': {
      id: '/_authenticated/admin/reddit/$id'
      path: '/$id'
      fullPath: '/admin/reddit/$id'
      preLoaderRoute: typeof AuthenticatedAdminRedditIdRouteImport
      parentRoute: typeof AuthenticatedAdminRedditRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedAdminPostsRoute
    }
  }
}

interface AuthenticatedAdminPostsRouteChildren {
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
}

const AuthenticatedAdminPostsRouteChildren: AuthenticatedAdminPostsRouteChildren =
  {
    AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
  }

const AuthenticatedAdminPostsRouteWithChildren =
  AuthenticatedAdminPostsRoute._addFileChildren(
    AuthenticatedAdminPostsRouteChildren,
  )

interface AuthenticatedAdminRedditRouteChildren {
  AuthenticatedAdminRedditIdRoute: typeof AuthenticatedAdminRedditIdRoute
}

const AuthenticatedAdminRedditRouteChildren: AuthenticatedAdminRedditRouteChildren =
  {
    AuthenticatedAdminRedditIdRoute: AuthenticatedAdminRedditIdRoute,
  }

const AuthenticatedAdminRedditRouteWithChildren =
  AuthenticatedAdminRedditRoute._addFileChildren(
    AuthenticatedAdminRedditRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiLogRoute: typeof AuthenticatedAdminAiLogRoute
  AuthenticatedAdminAuthorsRoute: typeof AuthenticatedAdminAuthorsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRouteWithChildren
  AuthenticatedAdminRedditRoute: typeof AuthenticatedAdminRedditRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiLogRoute: AuthenticatedAdminAiLogRoute,
  AuthenticatedAdminAuthorsRoute: AuthenticatedAdminAuthorsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRouteWithChildren,
  AuthenticatedAdminRedditRoute: AuthenticatedAdminRedditRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsLocalRoute: typeof NewsLocalRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsLocalRoute: NewsLocalRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdvertiseRoute: AdvertiseRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CorrectionsPolicyRoute: CorrectionsPolicyRoute,
  NewsRoute: NewsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PublicFileRoute: PublicFileRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  ShowsRoute: ShowsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  SubmitNewsTipRoute: SubmitNewsTipRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  WatchLiveRoute: WatchLiveRoute,
  WeatherRoute: WeatherRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiPublicHooksProcessPendingRoute: ApiPublicHooksProcessPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
